package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AddressType generated by hbm2java
 */
public class AddressType  implements java.io.Serializable {


     private Integer id;
     private String desc;
     private Set addresseses = new HashSet(0);

    public AddressType() {
    }

	
    public AddressType(String desc) {
        this.desc = desc;
    }
    public AddressType(String desc, Set addresseses) {
       this.desc = desc;
       this.addresseses = addresseses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public Set getAddresseses() {
        return this.addresseses;
    }
    
    public void setAddresseses(Set addresseses) {
        this.addresseses = addresseses;
    }




}


