package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ChartOfAccounts generated by hbm2java
 */
public class ChartOfAccounts  implements java.io.Serializable {


     private String code;
     private String name;
     private Set partnerAccountingsForAccountPayable = new HashSet(0);
     private Set partnerAccountingsForAccountReceivable = new HashSet(0);

    public ChartOfAccounts() {
    }

	
    public ChartOfAccounts(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public ChartOfAccounts(String code, String name, Set partnerAccountingsForAccountPayable, Set partnerAccountingsForAccountReceivable) {
       this.code = code;
       this.name = name;
       this.partnerAccountingsForAccountPayable = partnerAccountingsForAccountPayable;
       this.partnerAccountingsForAccountReceivable = partnerAccountingsForAccountReceivable;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getPartnerAccountingsForAccountPayable() {
        return this.partnerAccountingsForAccountPayable;
    }
    
    public void setPartnerAccountingsForAccountPayable(Set partnerAccountingsForAccountPayable) {
        this.partnerAccountingsForAccountPayable = partnerAccountingsForAccountPayable;
    }
    public Set getPartnerAccountingsForAccountReceivable() {
        return this.partnerAccountingsForAccountReceivable;
    }
    
    public void setPartnerAccountingsForAccountReceivable(Set partnerAccountingsForAccountReceivable) {
        this.partnerAccountingsForAccountReceivable = partnerAccountingsForAccountReceivable;
    }




}


