package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChartOfAccountsEntry generated by hbm2java
 */
@Entity
@Table(name = "chart_of_accounts")
public class ChartOfAccountsEntry implements java.io.Serializable {

    private String code;
    private String name;

    public ChartOfAccountsEntry() {
    }

    public ChartOfAccountsEntry(String code, String name) {
        this.code = code;
        this.name = name;
    }

    @Id
    @Column(name = "code")
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
