package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

    private Integer id;
    private Partner partners;
    private UnitOfMeasurement unitOfMeasurement;
    private String name;
    private float saleValue;
    private float purchaseValue;
    private boolean canBeSold;
    private boolean canBePurchased;
    private Date createdAt;
    private Date updatedAt;
    private int createdBy;
    private int updatedBy;

    public Item() {
    }

    public Item(UnitOfMeasurement unitOfMeasurement, String name, float saleValue, float purchaseValue, boolean canBeSold, boolean canBePurchased, Date createdAt, Date updatedAt, int createdBy, int updatedBy) {
        this.unitOfMeasurement = unitOfMeasurement;
        this.name = name;
        this.saleValue = saleValue;
        this.purchaseValue = purchaseValue;
        this.canBeSold = canBeSold;
        this.canBePurchased = canBePurchased;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }

    public Item(Partner partners, UnitOfMeasurement unitsOfMeasurement, String name, float saleValue, float purchaseValue, boolean canBeSold, boolean canBePurchased, Date createdAt, Date updatedAt, int createdBy, int updatedBy) {
        this.partners = partners;
        this.unitOfMeasurement = unitsOfMeasurement;
        this.name = name;
        this.saleValue = saleValue;
        this.purchaseValue = purchaseValue;
        this.canBeSold = canBeSold;
        this.canBePurchased = canBePurchased;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Partner getPartners() {
        return this.partners;
    }

    public void setPartners(Partner partners) {
        this.partners = partners;
    }

    public UnitOfMeasurement getUnitOfMeasurement() {
        return this.unitOfMeasurement;
    }

    public void setUnitOfMeasurement(UnitOfMeasurement unitOfMeasurement) {
        this.unitOfMeasurement = unitOfMeasurement;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public float getSaleValue() {
        return this.saleValue;
    }

    public void setSaleValue(float saleValue) {
        this.saleValue = saleValue;
    }

    public float getPurchaseValue() {
        return this.purchaseValue;
    }

    public void setPurchaseValue(float purchaseValue) {
        this.purchaseValue = purchaseValue;
    }

    public boolean isCanBeSold() {
        return this.canBeSold;
    }

    public void setCanBeSold(boolean canBeSold) {
        this.canBeSold = canBeSold;
    }

    public boolean isCanBePurchased() {
        return this.canBePurchased;
    }

    public void setCanBePurchased(boolean canBePurchased) {
        this.canBePurchased = canBePurchased;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    public int getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(int updatedBy) {
        this.updatedBy = updatedBy;
    }

}
