package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Partner generated by hbm2java
 */
@Entity
@Table(name = "partners")
public class Partner implements java.io.Serializable {

    private Integer id;
    private PartnerType partnerType;
    private Partner company;
    private String name;
    private Set partnerAccountingDetails = new HashSet(0);
    private Set addresses = new HashSet(0);

    public Partner() {
    }

    public Partner(PartnerType partnerType, String name) {
        this.partnerType = partnerType;
        this.name = name;
    }

    public Partner(PartnerType partnerType, String name, Set partnerAccountingDetails, Partner company, Set addresses) {
        this.partnerType = partnerType;
        this.name = name;
        this.partnerAccountingDetails = partnerAccountingDetails;
        this.company = company;
        this.addresses = addresses;
    }

    @Id
    @GeneratedValue
    @Column(name = "id")
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @OneToOne(targetEntity = PartnerType.class, fetch = FetchType.EAGER)
    public PartnerType getPartnerType() {
        return this.partnerType;
    }

    public void setPartnerType(PartnerType partnerType) {
        this.partnerType = partnerType;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToOne(targetEntity = PartnerAccountingDetail.class, fetch = FetchType.EAGER)
    public Set getPartnerAccountingDetails() {
        return this.partnerAccountingDetails;
    }

    public void setPartnerAccountingDetails(Set partnerAccountingDetails) {
        this.partnerAccountingDetails = partnerAccountingDetails;
    }

    @OneToOne(targetEntity = Partner.class, fetch = FetchType.EAGER)
    public Partner getCompany() {
        return this.company;
    }

    public void setCompany(Partner company) {
        this.company = company;
    }

    @OneToMany(targetEntity = Address.class, fetch = FetchType.LAZY)
    public Set getAddresses() {
        return this.addresses;
    }

    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }

}
