package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PartnerType generated by hbm2java
 */
public class PartnerType  implements java.io.Serializable {


     private Integer id;
     private String desc;
     private Set partnerses = new HashSet(0);

    public PartnerType() {
    }

	
    public PartnerType(String desc) {
        this.desc = desc;
    }
    public PartnerType(String desc, Set partnerses) {
       this.desc = desc;
       this.partnerses = partnerses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public Set getPartnerses() {
        return this.partnerses;
    }
    
    public void setPartnerses(Set partnerses) {
        this.partnerses = partnerses;
    }




}


