package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Partner generated by hbm2java
 */
public class Partner implements java.io.Serializable {

    private Integer id;
    private PartnerType partnerType;
    private Partner partners;
    private String name;
    private Set partnerAccountings = new HashSet(0);
    private Set itemses = new HashSet(0);
    private Set partnerses = new HashSet(0);
    private Set addresseses = new HashSet(0);

    public Partner() {
    }

    public Partner(PartnerType partnerType, String name) {
        this.partnerType = partnerType;
        this.name = name;
    }

    public Partner(PartnerType partnerType, Partner partners, String name, Set partnerAccountings, Set itemses, Set partnerses, Set addresseses) {
        this.partnerType = partnerType;
        this.partners = partners;
        this.name = name;
        this.partnerAccountings = partnerAccountings;
        this.itemses = itemses;
        this.partnerses = partnerses;
        this.addresseses = addresseses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public PartnerType getPartnerType() {
        return this.partnerType;
    }

    public void setPartnerType(PartnerType partnerType) {
        this.partnerType = partnerType;
    }

    public Partner getPartners() {
        return this.partners;
    }

    public void setPartners(Partner partners) {
        this.partners = partners;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getPartnerAccountings() {
        return this.partnerAccountings;
    }

    public void setPartnerAccountings(Set partnerAccountings) {
        this.partnerAccountings = partnerAccountings;
    }

    public Set getItemses() {
        return this.itemses;
    }

    public void setItemses(Set itemses) {
        this.itemses = itemses;
    }

    public Set getPartnerses() {
        return this.partnerses;
    }

    public void setPartnerses(Set partnerses) {
        this.partnerses = partnerses;
    }

    public Set getAddresseses() {
        return this.addresseses;
    }

    public void setAddresseses(Set addresseses) {
        this.addresseses = addresseses;
    }

}
