package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PaymentTerm generated by hbm2java
 */
@Entity
@Table(name = "payment_terms")
public class PaymentTerm implements java.io.Serializable {

    private Integer id;
    private String desc;

    public PaymentTerm() {
    }

    public PaymentTerm(String desc) {
        this.desc = desc;
    }

    @Id
    @Column(name = "id")
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "desc")
    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }
}
