package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * PaymentTerm generated by hbm2java
 */
public class PaymentTerm implements java.io.Serializable {

    private Integer id;
    private String desc;
    private Set partnerAccountingsForCustomerPaymentTermId = new HashSet(0);
    private Set partnerAccountingsForVendorPaymentTermId = new HashSet(0);

    public PaymentTerm() {
    }

    public PaymentTerm(String desc) {
        this.desc = desc;
    }

    public PaymentTerm(String desc, Set partnerAccountingsForCustomerPaymentTermId, Set partnerAccountingsForVendorPaymentTermId) {
        this.desc = desc;
        this.partnerAccountingsForCustomerPaymentTermId = partnerAccountingsForCustomerPaymentTermId;
        this.partnerAccountingsForVendorPaymentTermId = partnerAccountingsForVendorPaymentTermId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Set getPartnerAccountingsForCustomerPaymentTermId() {
        return this.partnerAccountingsForCustomerPaymentTermId;
    }

    public void setPartnerAccountingsForCustomerPaymentTermId(Set partnerAccountingsForCustomerPaymentTermId) {
        this.partnerAccountingsForCustomerPaymentTermId = partnerAccountingsForCustomerPaymentTermId;
    }

    public Set getPartnerAccountingsForVendorPaymentTermId() {
        return this.partnerAccountingsForVendorPaymentTermId;
    }

    public void setPartnerAccountingsForVendorPaymentTermId(Set partnerAccountingsForVendorPaymentTermId) {
        this.partnerAccountingsForVendorPaymentTermId = partnerAccountingsForVendorPaymentTermId;
    }

}
