package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * UnitOfMeasurement generated by hbm2java
 */
@Entity
@Table(name = "units_of_measurement")
public class UnitOfMeasurement implements java.io.Serializable {

    private long id;
    private String name;
    private Set items = new HashSet(0);

    public UnitOfMeasurement() {
    }

    public UnitOfMeasurement(String name) {
        this.name = name;
    }

    public UnitOfMeasurement(String name, Set itemses) {
        this.name = name;
        this.items = itemses;
    }

    @Id
    @GeneratedValue
    @Column(name = "id")
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToOne(targetEntity = Item.class)
//    @JoinColumn(name = "id", referencedColumnName = "unit_of_measurement_id")
    public Set getItems() {
        return this.items;
    }

    public void setItems(Set items) {
        this.items = items;
    }

}
