package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * UnitOfMeasurement generated by hbm2java
 */
public class UnitOfMeasurement implements java.io.Serializable {

    private Integer id;
    private String name;
    private Set items = new HashSet(0);

    public UnitOfMeasurement() {
    }

    public UnitOfMeasurement(String name) {
        this.name = name;
    }

    public UnitOfMeasurement(String name, Set itemses) {
        this.name = name;
        this.items = itemses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getItems() {
        return this.items;
    }

    public void setItems(Set items) {
        this.items = items;
    }

}
