package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

    private Integer id;
    private User users;
    private String role;

    public UserRole() {
    }

    public UserRole(User users, String role) {
        this.users = users;
        this.role = role;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public User getUsers() {
        return this.users;
    }

    public void setUsers(User users) {
        this.users = users;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

}
