package com.flow.inventory.model;
// Generated Mar 10, 2016 2:37:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private Integer id;
    private String email;
    private boolean isActive;
    private String displayName;
    private String password;
    private Set userRoles = new HashSet(0);

    public User() {
    }

    public User(String email, boolean isActive, String displayName, String password) {
        this.email = email;
        this.isActive = isActive;
        this.displayName = displayName;
        this.password = password;
    }

    public User(String email, boolean isActive, String displayName, String password, Set userRoles) {
        this.email = email;
        this.isActive = isActive;
        this.displayName = displayName;
        this.password = password;
        this.userRoles = userRoles;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public boolean isIsActive() {
        return this.isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    public String getDisplayName() {
        return this.displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set getUserRoles() {
        return this.userRoles;
    }

    public void setUserRoles(Set userRoles) {
        this.userRoles = userRoles;
    }

}
